### ISSUE TITLE
Plans for releasing 0.2?

### ISSUE THREAD

**Issue by musicinmybrain** [hgrecco/flexparser#5]
Since https://github.com/hgrecco/pint is using a vendored copy of `flexparser` taken from somewhere around 49e5c1154dd54640fc7fb7852b73d8e69407e684, with a number of changes not in the 0.1 release, is a 0.2 release planned any time soon?

In Fedora Linux, we’d rather de-vendor `flexparser` and use an external copy as part of a general policy of avoiding bundled libraries [except under certain conditions](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling). This is pretty easy to do, but it would be nice if the packaged `flexparser` could be a tagged/stable release rather than a pre-release snapshot. I understand, though, that the vendored copy in `pint` works, and from your perspective this isn’t a problem or something you *need* to do anything about.

**Comment by hgrecco** [comment]
Given what you suggest, I could release a new flexparser version. I will do it over the weekend.

**Comment by musicinmybrain** [comment]
Are you still planning a 0.2 release? Thanks!

**Comment by hgrecco** [comment]
Done! Pint now uses flexparser 0.2

By the way, is there anything we can do from pint/flexparser to make things easier for Fedora?

**Comment by hgrecco** [comment]
I will consider this into Pint! thanks!
