### ISSUE TITLE
Cannot be successfully imported in Python without `blake2b` hashing algorithm

### ISSUE THREAD

**Issue by stevecj** [hgrecco/flexparser#6]
I have a project using `Pint` that fails using our latest build of Python that uses the OpenSSL 3 libraries because Python does not support the legacy `blake2b` algorithm in that case.

I also can't monkey-patch around the issue because the code in` flexparser` that references `hashlib.blake2b` is in the main body of the `Parser` class definition and executes during import of the file.

**Comment by hgrecco** [comment]
Can you expand on this? As you mention, `flexparsers` uses `blake2b` that is included in python's standard library module `hashlib`. Are you using a custom python build?

**Comment by stevecj** [comment]
Yes. I am using a custom Python build. I finally figured out it is because Python requires libb2 to provide that algorithm, and that library was typically installed by default in rhel7 but not rhel8. I am able to work around the problem by making sure that library in installed.

From what I understand (correctly or incorrectly) that is a legacy algorithm and will become less and less available from now on. It seems like, at least, there should be some way to configure a different algorithm to use before code executes that depends on the algorithm being available in the current Python implementation.

**Comment by hgrecco** [comment]
My understanding from [this](https://docs.python.org/3/library/hashlib.html#hashlib.algorithms_guaranteed) was that blake2 was supposed to work in all platforms. In any case, I do agree that we need a way to make this work. Configuring is a good option. But as the hasher is (most of the times) an internal detail I would like something that just works in most cases and manual configuration should only be used in a small number of cases.

How about the following: 
1. within `flexparser` we list suitable algorithms sorted according to some rationale (e.g. faster and safer first)
2. upon importing, we check if a environ flag is set (e.g. `FLEXPARSER_HASH_ALGORITHM`)
2.1. If present, we insantiate that hasher
2.2. If not, we move through the list mentioned in (1) until a working algortihm is found.

**Comment by stevecj** [comment]
That sounds good, and actually, with the iteration in place, I would think that the configuration option is probably unnecessary. As you say, that should ideally be an implementation detail.

**Comment by hgrecco** [comment]
Just fixed. It works like this:


1. Within flexparser there is a list of suitable algorithms `_HASH_ALGORITHMS`
2. Upon import, flexparser will try them (hash something and get the hexdigest) one by one until one works. This will become the default hasher (and stored in _DEFAULT_HASHER)
3. If no algorithm work, a dummy function that raise an error message with a possible solution will be created. Also, a warning will be issued

**Comment by stevecj** [comment]
Awesome. 👍 Thanks.
